### ISSUE TITLE
Não funciona corretamente no Firefox

### ISSUE THREAD

**Issue by andreldm** [alexsad/guessit-frontend#1]
Estou sendo obrigado a usar o Chromium :angry:

**Comment by ferrugemjs** [comment]
atualiza o projeto
git pull
npm install
jspm install

**Comment by andreldm** [comment]
Já tinha feito isso, agora até no chromium tá intermitente, tem hora que funciona direito mas na maioria das vezes quando uma carta é seleciona ela não aparece, fica só um "ok" no canto superior esquerdo.
Também tem vez que as cartas são carregadas fora da barrinha inferior.

Vide screenshots:

![screenshot_2016-09-03_11-52-47](https://cloud.githubusercontent.com/assets/599565/18225608/e38d9e7e-71cc-11e6-997f-0149e701b38f.png)
![screenshot_2016-09-03_11-53-05](https://cloud.githubusercontent.com/assets/599565/18225609/e38ef3b4-71cc-11e6-8f0f-2ca86b54632a.png)

**Comment by ferrugemjs** [comment]
estou desconfiado que seja o css que não esta sendo carregado em alguns momentos
quando tu terminar os canais do socket me avisa que eu já testo aqui esse bug.

**Comment by alexsad** [comment]
No meu IE 7 funciona direitinho.

**Comment by alexsad** [comment]
resolvido na versão atual
