### ISSUE TITLE
Voltar para carta default

### ISSUE THREAD

**Issue by andreldm** [alexsad/guessit-frontend#3]
Passos para reproduzir o bug:
1 - comece o jogo com três jogados (A,B,C)
2 - O jogador A escolhe uma carta e os demais escolhem as cartas
3 - O jogador B escolhe uma carta e vota, antes do jogador C ele escolhe novamente uma carta
4 - Quando o jogador C confirmar a escolha e for a vez do jogador B, o mesmo poderá escolher a carta que nem era dele.

Solução: ao receber os sinais pick-card e pick-bet voltar para a carta default.

**Comment by alexsad** [comment]
corrigido vlw!!!
